apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: my-app
build:
  artifacts:
  - image: taslim1995/nextjs-demo
    docker:
      dockerfile: Dockerfile
test:
  - context: .
    image: taslim1995/nextjs-demo
    custom:
      - command: npm run test
deploy:
  kubectl:
    manifests:
    - deployment-config/*